//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Laba3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Автомобили.
    /// </summary>
    // *** Start programmer edit section *** (Автомобили CustomAttributes)

    // *** End programmer edit section *** (Автомобили CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Автомобили : ICSSoft.STORMNET.DataObject
    {
        
        private int fIDАвто;
        
        private string fМарка;
        
        private string fГосНомерАвто;
        
        // *** Start programmer edit section *** (Автомобили CustomMembers)

        // *** End programmer edit section *** (Автомобили CustomMembers)

        
        /// <summary>
        /// IDАвто.
        /// </summary>
        // *** Start programmer edit section *** (Автомобили.IDАвто CustomAttributes)

        // *** End programmer edit section *** (Автомобили.IDАвто CustomAttributes)
        public virtual int IDАвто
        {
            get
            {
                // *** Start programmer edit section *** (Автомобили.IDАвто Get start)

                // *** End programmer edit section *** (Автомобили.IDАвто Get start)
                int result = this.fIDАвто;
                // *** Start programmer edit section *** (Автомобили.IDАвто Get end)

                // *** End programmer edit section *** (Автомобили.IDАвто Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Автомобили.IDАвто Set start)

                // *** End programmer edit section *** (Автомобили.IDАвто Set start)
                this.fIDАвто = value;
                // *** Start programmer edit section *** (Автомобили.IDАвто Set end)

                // *** End programmer edit section *** (Автомобили.IDАвто Set end)
            }
        }
        
        /// <summary>
        /// ГосНомерАвто.
        /// </summary>
        // *** Start programmer edit section *** (Автомобили.ГосНомерАвто CustomAttributes)

        // *** End programmer edit section *** (Автомобили.ГосНомерАвто CustomAttributes)
        [StrLen(255)]
        public virtual string ГосНомерАвто
        {
            get
            {
                // *** Start programmer edit section *** (Автомобили.ГосНомерАвто Get start)

                // *** End programmer edit section *** (Автомобили.ГосНомерАвто Get start)
                string result = this.fГосНомерАвто;
                // *** Start programmer edit section *** (Автомобили.ГосНомерАвто Get end)

                // *** End programmer edit section *** (Автомобили.ГосНомерАвто Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Автомобили.ГосНомерАвто Set start)

                // *** End programmer edit section *** (Автомобили.ГосНомерАвто Set start)
                this.fГосНомерАвто = value;
                // *** Start programmer edit section *** (Автомобили.ГосНомерАвто Set end)

                // *** End programmer edit section *** (Автомобили.ГосНомерАвто Set end)
            }
        }
        
        /// <summary>
        /// Марка.
        /// </summary>
        // *** Start programmer edit section *** (Автомобили.Марка CustomAttributes)

        // *** End programmer edit section *** (Автомобили.Марка CustomAttributes)
        [StrLen(255)]
        public virtual string Марка
        {
            get
            {
                // *** Start programmer edit section *** (Автомобили.Марка Get start)

                // *** End programmer edit section *** (Автомобили.Марка Get start)
                string result = this.fМарка;
                // *** Start programmer edit section *** (Автомобили.Марка Get end)

                // *** End programmer edit section *** (Автомобили.Марка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Автомобили.Марка Set start)

                // *** End programmer edit section *** (Автомобили.Марка Set start)
                this.fМарка = value;
                // *** Start programmer edit section *** (Автомобили.Марка Set end)

                // *** End programmer edit section *** (Автомобили.Марка Set end)
            }
        }
    }
}
