//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Laba3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// АктПогрРазгр.
    /// </summary>
    // *** Start programmer edit section *** (АктПогрРазгр CustomAttributes)

    // *** End programmer edit section *** (АктПогрРазгр CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class АктПогрРазгр : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Laba3.ТипАкта fТип;
        
        private IIS.Laba3.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (АктПогрРазгр CustomMembers)

        // *** End programmer edit section *** (АктПогрРазгр CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (АктПогрРазгр.Дата CustomAttributes)

        // *** End programmer edit section *** (АктПогрРазгр.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (АктПогрРазгр.Дата Get start)

                // *** End programmer edit section *** (АктПогрРазгр.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (АктПогрРазгр.Дата Get end)

                // *** End programmer edit section *** (АктПогрРазгр.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктПогрРазгр.Дата Set start)

                // *** End programmer edit section *** (АктПогрРазгр.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (АктПогрРазгр.Дата Set end)

                // *** End programmer edit section *** (АктПогрРазгр.Дата Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (АктПогрРазгр.Тип CustomAttributes)

        // *** End programmer edit section *** (АктПогрРазгр.Тип CustomAttributes)
        public virtual IIS.Laba3.ТипАкта Тип
        {
            get
            {
                // *** Start programmer edit section *** (АктПогрРазгр.Тип Get start)

                // *** End programmer edit section *** (АктПогрРазгр.Тип Get start)
                IIS.Laba3.ТипАкта result = this.fТип;
                // *** Start programmer edit section *** (АктПогрРазгр.Тип Get end)

                // *** End programmer edit section *** (АктПогрРазгр.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктПогрРазгр.Тип Set start)

                // *** End programmer edit section *** (АктПогрРазгр.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (АктПогрРазгр.Тип Set end)

                // *** End programmer edit section *** (АктПогрРазгр.Тип Set end)
            }
        }
        
        /// <summary>
        /// АктПогрРазгр.
        /// </summary>
        // *** Start programmer edit section *** (АктПогрРазгр.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (АктПогрРазгр.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Laba3.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (АктПогрРазгр.Сотрудники Get start)

                // *** End programmer edit section *** (АктПогрРазгр.Сотрудники Get start)
                IIS.Laba3.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (АктПогрРазгр.Сотрудники Get end)

                // *** End programmer edit section *** (АктПогрРазгр.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (АктПогрРазгр.Сотрудники Set start)

                // *** End programmer edit section *** (АктПогрРазгр.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (АктПогрРазгр.Сотрудники Set end)

                // *** End programmer edit section *** (АктПогрРазгр.Сотрудники Set end)
            }
        }
    }
}
