//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Laba3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должности.
    /// </summary>
    // *** Start programmer edit section *** (Должности CustomAttributes)

    // *** End programmer edit section *** (Должности CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Должности : ICSSoft.STORMNET.DataObject
    {
        
        private int fIDДолжности;
        
        private string fНаимДолжности;
        
        // *** Start programmer edit section *** (Должности CustomMembers)

        // *** End programmer edit section *** (Должности CustomMembers)

        
        /// <summary>
        /// IDДолжности.
        /// </summary>
        // *** Start programmer edit section *** (Должности.IDДолжности CustomAttributes)

        // *** End programmer edit section *** (Должности.IDДолжности CustomAttributes)
        public virtual int IDДолжности
        {
            get
            {
                // *** Start programmer edit section *** (Должности.IDДолжности Get start)

                // *** End programmer edit section *** (Должности.IDДолжности Get start)
                int result = this.fIDДолжности;
                // *** Start programmer edit section *** (Должности.IDДолжности Get end)

                // *** End programmer edit section *** (Должности.IDДолжности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должности.IDДолжности Set start)

                // *** End programmer edit section *** (Должности.IDДолжности Set start)
                this.fIDДолжности = value;
                // *** Start programmer edit section *** (Должности.IDДолжности Set end)

                // *** End programmer edit section *** (Должности.IDДолжности Set end)
            }
        }
        
        /// <summary>
        /// НаимДолжности.
        /// </summary>
        // *** Start programmer edit section *** (Должности.НаимДолжности CustomAttributes)

        // *** End programmer edit section *** (Должности.НаимДолжности CustomAttributes)
        [StrLen(255)]
        public virtual string НаимДолжности
        {
            get
            {
                // *** Start programmer edit section *** (Должности.НаимДолжности Get start)

                // *** End programmer edit section *** (Должности.НаимДолжности Get start)
                string result = this.fНаимДолжности;
                // *** Start programmer edit section *** (Должности.НаимДолжности Get end)

                // *** End programmer edit section *** (Должности.НаимДолжности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должности.НаимДолжности Set start)

                // *** End programmer edit section *** (Должности.НаимДолжности Set start)
                this.fНаимДолжности = value;
                // *** Start programmer edit section *** (Должности.НаимДолжности Set end)

                // *** End programmer edit section *** (Должности.НаимДолжности Set end)
            }
        }
    }
}
