//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Laba3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ЖурналСостТС.
    /// </summary>
    // *** Start programmer edit section *** (ЖурналСостТС CustomAttributes)

    // *** End programmer edit section *** (ЖурналСостТС CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ЖурналСостТС : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fПоказОдометра;
        
        private int fВремя;
        
        private string fВнешСостТС;
        
        private IIS.Laba3.Автомобили fАвтомобили;
        
        private IIS.Laba3.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (ЖурналСостТС CustomMembers)

        // *** End programmer edit section *** (ЖурналСостТС CustomMembers)

        
        /// <summary>
        /// ВнешСостТС.
        /// </summary>
        // *** Start programmer edit section *** (ЖурналСостТС.ВнешСостТС CustomAttributes)

        // *** End programmer edit section *** (ЖурналСостТС.ВнешСостТС CustomAttributes)
        [StrLen(255)]
        public virtual string ВнешСостТС
        {
            get
            {
                // *** Start programmer edit section *** (ЖурналСостТС.ВнешСостТС Get start)

                // *** End programmer edit section *** (ЖурналСостТС.ВнешСостТС Get start)
                string result = this.fВнешСостТС;
                // *** Start programmer edit section *** (ЖурналСостТС.ВнешСостТС Get end)

                // *** End programmer edit section *** (ЖурналСостТС.ВнешСостТС Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖурналСостТС.ВнешСостТС Set start)

                // *** End programmer edit section *** (ЖурналСостТС.ВнешСостТС Set start)
                this.fВнешСостТС = value;
                // *** Start programmer edit section *** (ЖурналСостТС.ВнешСостТС Set end)

                // *** End programmer edit section *** (ЖурналСостТС.ВнешСостТС Set end)
            }
        }
        
        /// <summary>
        /// Время.
        /// </summary>
        // *** Start programmer edit section *** (ЖурналСостТС.Время CustomAttributes)

        // *** End programmer edit section *** (ЖурналСостТС.Время CustomAttributes)
        public virtual int Время
        {
            get
            {
                // *** Start programmer edit section *** (ЖурналСостТС.Время Get start)

                // *** End programmer edit section *** (ЖурналСостТС.Время Get start)
                int result = this.fВремя;
                // *** Start programmer edit section *** (ЖурналСостТС.Время Get end)

                // *** End programmer edit section *** (ЖурналСостТС.Время Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖурналСостТС.Время Set start)

                // *** End programmer edit section *** (ЖурналСостТС.Время Set start)
                this.fВремя = value;
                // *** Start programmer edit section *** (ЖурналСостТС.Время Set end)

                // *** End programmer edit section *** (ЖурналСостТС.Время Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ЖурналСостТС.Дата CustomAttributes)

        // *** End programmer edit section *** (ЖурналСостТС.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ЖурналСостТС.Дата Get start)

                // *** End programmer edit section *** (ЖурналСостТС.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ЖурналСостТС.Дата Get end)

                // *** End programmer edit section *** (ЖурналСостТС.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖурналСостТС.Дата Set start)

                // *** End programmer edit section *** (ЖурналСостТС.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ЖурналСостТС.Дата Set end)

                // *** End programmer edit section *** (ЖурналСостТС.Дата Set end)
            }
        }
        
        /// <summary>
        /// ПоказОдометра.
        /// </summary>
        // *** Start programmer edit section *** (ЖурналСостТС.ПоказОдометра CustomAttributes)

        // *** End programmer edit section *** (ЖурналСостТС.ПоказОдометра CustomAttributes)
        public virtual int ПоказОдометра
        {
            get
            {
                // *** Start programmer edit section *** (ЖурналСостТС.ПоказОдометра Get start)

                // *** End programmer edit section *** (ЖурналСостТС.ПоказОдометра Get start)
                int result = this.fПоказОдометра;
                // *** Start programmer edit section *** (ЖурналСостТС.ПоказОдометра Get end)

                // *** End programmer edit section *** (ЖурналСостТС.ПоказОдометра Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖурналСостТС.ПоказОдометра Set start)

                // *** End programmer edit section *** (ЖурналСостТС.ПоказОдометра Set start)
                this.fПоказОдометра = value;
                // *** Start programmer edit section *** (ЖурналСостТС.ПоказОдометра Set end)

                // *** End programmer edit section *** (ЖурналСостТС.ПоказОдометра Set end)
            }
        }
        
        /// <summary>
        /// ЖурналСостТС.
        /// </summary>
        // *** Start programmer edit section *** (ЖурналСостТС.Автомобили CustomAttributes)

        // *** End programmer edit section *** (ЖурналСостТС.Автомобили CustomAttributes)
        [PropertyStorage(new string[] {
                "Автомобили"})]
        [NotNull()]
        public virtual IIS.Laba3.Автомобили Автомобили
        {
            get
            {
                // *** Start programmer edit section *** (ЖурналСостТС.Автомобили Get start)

                // *** End programmer edit section *** (ЖурналСостТС.Автомобили Get start)
                IIS.Laba3.Автомобили result = this.fАвтомобили;
                // *** Start programmer edit section *** (ЖурналСостТС.Автомобили Get end)

                // *** End programmer edit section *** (ЖурналСостТС.Автомобили Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖурналСостТС.Автомобили Set start)

                // *** End programmer edit section *** (ЖурналСостТС.Автомобили Set start)
                this.fАвтомобили = value;
                // *** Start programmer edit section *** (ЖурналСостТС.Автомобили Set end)

                // *** End programmer edit section *** (ЖурналСостТС.Автомобили Set end)
            }
        }
        
        /// <summary>
        /// ЖурналСостТС.
        /// </summary>
        // *** Start programmer edit section *** (ЖурналСостТС.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ЖурналСостТС.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Laba3.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ЖурналСостТС.Сотрудники Get start)

                // *** End programmer edit section *** (ЖурналСостТС.Сотрудники Get start)
                IIS.Laba3.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ЖурналСостТС.Сотрудники Get end)

                // *** End programmer edit section *** (ЖурналСостТС.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЖурналСостТС.Сотрудники Set start)

                // *** End programmer edit section *** (ЖурналСостТС.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ЖурналСостТС.Сотрудники Set end)

                // *** End programmer edit section *** (ЖурналСостТС.Сотрудники Set end)
            }
        }
    }
}
