//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Laba3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ПутевойЛист.
    /// </summary>
    // *** Start programmer edit section *** (ПутевойЛист CustomAttributes)

    // *** End programmer edit section *** (ПутевойЛист CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ПутевойЛист : ICSSoft.STORMNET.DataObject
    {
        
        private string fДата;
        
        private IIS.Laba3.Сотрудники fСотрудники;
        
        private IIS.Laba3.Автомобили fАвтомобили;
        
        // *** Start programmer edit section *** (ПутевойЛист CustomMembers)

        // *** End programmer edit section *** (ПутевойЛист CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ПутевойЛист.Дата CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.Дата CustomAttributes)
        [StrLen(255)]
        public virtual string Дата
        {
            get
            {
                // *** Start programmer edit section *** (ПутевойЛист.Дата Get start)

                // *** End programmer edit section *** (ПутевойЛист.Дата Get start)
                string result = this.fДата;
                // *** Start programmer edit section *** (ПутевойЛист.Дата Get end)

                // *** End programmer edit section *** (ПутевойЛист.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПутевойЛист.Дата Set start)

                // *** End programmer edit section *** (ПутевойЛист.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ПутевойЛист.Дата Set end)

                // *** End programmer edit section *** (ПутевойЛист.Дата Set end)
            }
        }
        
        /// <summary>
        /// ПутевойЛист.
        /// </summary>
        // *** Start programmer edit section *** (ПутевойЛист.Автомобили CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.Автомобили CustomAttributes)
        [PropertyStorage(new string[] {
                "Автомобили"})]
        [NotNull()]
        public virtual IIS.Laba3.Автомобили Автомобили
        {
            get
            {
                // *** Start programmer edit section *** (ПутевойЛист.Автомобили Get start)

                // *** End programmer edit section *** (ПутевойЛист.Автомобили Get start)
                IIS.Laba3.Автомобили result = this.fАвтомобили;
                // *** Start programmer edit section *** (ПутевойЛист.Автомобили Get end)

                // *** End programmer edit section *** (ПутевойЛист.Автомобили Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПутевойЛист.Автомобили Set start)

                // *** End programmer edit section *** (ПутевойЛист.Автомобили Set start)
                this.fАвтомобили = value;
                // *** Start programmer edit section *** (ПутевойЛист.Автомобили Set end)

                // *** End programmer edit section *** (ПутевойЛист.Автомобили Set end)
            }
        }
        
        /// <summary>
        /// ПутевойЛист.
        /// </summary>
        // *** Start programmer edit section *** (ПутевойЛист.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ПутевойЛист.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Laba3.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ПутевойЛист.Сотрудники Get start)

                // *** End programmer edit section *** (ПутевойЛист.Сотрудники Get start)
                IIS.Laba3.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ПутевойЛист.Сотрудники Get end)

                // *** End programmer edit section *** (ПутевойЛист.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПутевойЛист.Сотрудники Set start)

                // *** End programmer edit section *** (ПутевойЛист.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ПутевойЛист.Сотрудники Set end)

                // *** End programmer edit section *** (ПутевойЛист.Сотрудники Set end)
            }
        }
    }
}
