//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Laba3
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТипАкта.
    /// </summary>
    // *** Start programmer edit section *** (ТипАкта CustomAttributes)

    // *** End programmer edit section *** (ТипАкта CustomAttributes)
    public enum ТипАкта
    {
        
        // *** Start programmer edit section *** (ТипАкта.Разгрузка CustomAttributes)

        // *** End programmer edit section *** (ТипАкта.Разгрузка CustomAttributes)
        Разгрузка,
        
        // *** Start programmer edit section *** (ТипАкта.Погрузка CustomAttributes)

        // *** End programmer edit section *** (ТипАкта.Погрузка CustomAttributes)
        Погрузка,
    }
}
