//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Laba3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар.
    /// </summary>
    // *** Start programmer edit section *** (Товар CustomAttributes)

    // *** End programmer edit section *** (Товар CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Товар : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаимТовара;
        
        private int fIDТовара;
        
        // *** Start programmer edit section *** (Товар CustomMembers)

        // *** End programmer edit section *** (Товар CustomMembers)

        
        /// <summary>
        /// IDТовара.
        /// </summary>
        // *** Start programmer edit section *** (Товар.IDТовара CustomAttributes)

        // *** End programmer edit section *** (Товар.IDТовара CustomAttributes)
        public virtual int IDТовара
        {
            get
            {
                // *** Start programmer edit section *** (Товар.IDТовара Get start)

                // *** End programmer edit section *** (Товар.IDТовара Get start)
                int result = this.fIDТовара;
                // *** Start programmer edit section *** (Товар.IDТовара Get end)

                // *** End programmer edit section *** (Товар.IDТовара Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.IDТовара Set start)

                // *** End programmer edit section *** (Товар.IDТовара Set start)
                this.fIDТовара = value;
                // *** Start programmer edit section *** (Товар.IDТовара Set end)

                // *** End programmer edit section *** (Товар.IDТовара Set end)
            }
        }
        
        /// <summary>
        /// НаимТовара.
        /// </summary>
        // *** Start programmer edit section *** (Товар.НаимТовара CustomAttributes)

        // *** End programmer edit section *** (Товар.НаимТовара CustomAttributes)
        [StrLen(255)]
        public virtual string НаимТовара
        {
            get
            {
                // *** Start programmer edit section *** (Товар.НаимТовара Get start)

                // *** End programmer edit section *** (Товар.НаимТовара Get start)
                string result = this.fНаимТовара;
                // *** Start programmer edit section *** (Товар.НаимТовара Get end)

                // *** End programmer edit section *** (Товар.НаимТовара Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.НаимТовара Set start)

                // *** End programmer edit section *** (Товар.НаимТовара Set start)
                this.fНаимТовара = value;
                // *** Start programmer edit section *** (Товар.НаимТовара Set end)

                // *** End programmer edit section *** (Товар.НаимТовара Set end)
            }
        }
    }
}
