//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Laba3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТЧАктПГ.
    /// </summary>
    // *** Start programmer edit section *** (ТЧАктПГ CustomAttributes)

    // *** End programmer edit section *** (ТЧАктПГ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ТЧАктПГ : ICSSoft.STORMNET.DataObject
    {
        
        private double fВесТовараКонец;
        
        private double fВремявПути;
        
        private string fОтклоненияВеса;
        
        private string fМестоРазгрузки;
        
        private double fВесТовараНачало;
        
        private string fМестоПогрузки;
        
        private IIS.Laba3.АктПогрРазгр fАктПогрРазгр;
        
        private IIS.Laba3.Товар fТовар;
        
        // *** Start programmer edit section *** (ТЧАктПГ CustomMembers)

        // *** End programmer edit section *** (ТЧАктПГ CustomMembers)

        
        /// <summary>
        /// ВесТовараКонец.
        /// </summary>
        // *** Start programmer edit section *** (ТЧАктПГ.ВесТовараКонец CustomAttributes)

        // *** End programmer edit section *** (ТЧАктПГ.ВесТовараКонец CustomAttributes)
        public virtual double ВесТовараКонец
        {
            get
            {
                // *** Start programmer edit section *** (ТЧАктПГ.ВесТовараКонец Get start)

                // *** End programmer edit section *** (ТЧАктПГ.ВесТовараКонец Get start)
                double result = this.fВесТовараКонец;
                // *** Start programmer edit section *** (ТЧАктПГ.ВесТовараКонец Get end)

                // *** End programmer edit section *** (ТЧАктПГ.ВесТовараКонец Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧАктПГ.ВесТовараКонец Set start)

                // *** End programmer edit section *** (ТЧАктПГ.ВесТовараКонец Set start)
                this.fВесТовараКонец = value;
                // *** Start programmer edit section *** (ТЧАктПГ.ВесТовараКонец Set end)

                // *** End programmer edit section *** (ТЧАктПГ.ВесТовараКонец Set end)
            }
        }
        
        /// <summary>
        /// ВесТовараНачало.
        /// </summary>
        // *** Start programmer edit section *** (ТЧАктПГ.ВесТовараНачало CustomAttributes)

        // *** End programmer edit section *** (ТЧАктПГ.ВесТовараНачало CustomAttributes)
        public virtual double ВесТовараНачало
        {
            get
            {
                // *** Start programmer edit section *** (ТЧАктПГ.ВесТовараНачало Get start)

                // *** End programmer edit section *** (ТЧАктПГ.ВесТовараНачало Get start)
                double result = this.fВесТовараНачало;
                // *** Start programmer edit section *** (ТЧАктПГ.ВесТовараНачало Get end)

                // *** End programmer edit section *** (ТЧАктПГ.ВесТовараНачало Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧАктПГ.ВесТовараНачало Set start)

                // *** End programmer edit section *** (ТЧАктПГ.ВесТовараНачало Set start)
                this.fВесТовараНачало = value;
                // *** Start programmer edit section *** (ТЧАктПГ.ВесТовараНачало Set end)

                // *** End programmer edit section *** (ТЧАктПГ.ВесТовараНачало Set end)
            }
        }
        
        /// <summary>
        /// ВремявПути.
        /// </summary>
        // *** Start programmer edit section *** (ТЧАктПГ.ВремявПути CustomAttributes)

        // *** End programmer edit section *** (ТЧАктПГ.ВремявПути CustomAttributes)
        public virtual double ВремявПути
        {
            get
            {
                // *** Start programmer edit section *** (ТЧАктПГ.ВремявПути Get start)

                // *** End programmer edit section *** (ТЧАктПГ.ВремявПути Get start)
                double result = this.fВремявПути;
                // *** Start programmer edit section *** (ТЧАктПГ.ВремявПути Get end)

                // *** End programmer edit section *** (ТЧАктПГ.ВремявПути Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧАктПГ.ВремявПути Set start)

                // *** End programmer edit section *** (ТЧАктПГ.ВремявПути Set start)
                this.fВремявПути = value;
                // *** Start programmer edit section *** (ТЧАктПГ.ВремявПути Set end)

                // *** End programmer edit section *** (ТЧАктПГ.ВремявПути Set end)
            }
        }
        
        /// <summary>
        /// МестоПогрузки.
        /// </summary>
        // *** Start programmer edit section *** (ТЧАктПГ.МестоПогрузки CustomAttributes)

        // *** End programmer edit section *** (ТЧАктПГ.МестоПогрузки CustomAttributes)
        [StrLen(255)]
        public virtual string МестоПогрузки
        {
            get
            {
                // *** Start programmer edit section *** (ТЧАктПГ.МестоПогрузки Get start)

                // *** End programmer edit section *** (ТЧАктПГ.МестоПогрузки Get start)
                string result = this.fМестоПогрузки;
                // *** Start programmer edit section *** (ТЧАктПГ.МестоПогрузки Get end)

                // *** End programmer edit section *** (ТЧАктПГ.МестоПогрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧАктПГ.МестоПогрузки Set start)

                // *** End programmer edit section *** (ТЧАктПГ.МестоПогрузки Set start)
                this.fМестоПогрузки = value;
                // *** Start programmer edit section *** (ТЧАктПГ.МестоПогрузки Set end)

                // *** End programmer edit section *** (ТЧАктПГ.МестоПогрузки Set end)
            }
        }
        
        /// <summary>
        /// МестоРазгрузки.
        /// </summary>
        // *** Start programmer edit section *** (ТЧАктПГ.МестоРазгрузки CustomAttributes)

        // *** End programmer edit section *** (ТЧАктПГ.МестоРазгрузки CustomAttributes)
        [StrLen(255)]
        public virtual string МестоРазгрузки
        {
            get
            {
                // *** Start programmer edit section *** (ТЧАктПГ.МестоРазгрузки Get start)

                // *** End programmer edit section *** (ТЧАктПГ.МестоРазгрузки Get start)
                string result = this.fМестоРазгрузки;
                // *** Start programmer edit section *** (ТЧАктПГ.МестоРазгрузки Get end)

                // *** End programmer edit section *** (ТЧАктПГ.МестоРазгрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧАктПГ.МестоРазгрузки Set start)

                // *** End programmer edit section *** (ТЧАктПГ.МестоРазгрузки Set start)
                this.fМестоРазгрузки = value;
                // *** Start programmer edit section *** (ТЧАктПГ.МестоРазгрузки Set end)

                // *** End programmer edit section *** (ТЧАктПГ.МестоРазгрузки Set end)
            }
        }
        
        /// <summary>
        /// ОтклоненияВеса.
        /// </summary>
        // *** Start programmer edit section *** (ТЧАктПГ.ОтклоненияВеса CustomAttributes)

        // *** End programmer edit section *** (ТЧАктПГ.ОтклоненияВеса CustomAttributes)
        [StrLen(255)]
        public virtual string ОтклоненияВеса
        {
            get
            {
                // *** Start programmer edit section *** (ТЧАктПГ.ОтклоненияВеса Get start)

                // *** End programmer edit section *** (ТЧАктПГ.ОтклоненияВеса Get start)
                string result = this.fОтклоненияВеса;
                // *** Start programmer edit section *** (ТЧАктПГ.ОтклоненияВеса Get end)

                // *** End programmer edit section *** (ТЧАктПГ.ОтклоненияВеса Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧАктПГ.ОтклоненияВеса Set start)

                // *** End programmer edit section *** (ТЧАктПГ.ОтклоненияВеса Set start)
                this.fОтклоненияВеса = value;
                // *** Start programmer edit section *** (ТЧАктПГ.ОтклоненияВеса Set end)

                // *** End programmer edit section *** (ТЧАктПГ.ОтклоненияВеса Set end)
            }
        }
        
        /// <summary>
        /// ТЧАктПГ.
        /// </summary>
        // *** Start programmer edit section *** (ТЧАктПГ.АктПогрРазгр CustomAttributes)

        // *** End programmer edit section *** (ТЧАктПГ.АктПогрРазгр CustomAttributes)
        [PropertyStorage(new string[] {
                "АктПогрРазгр"})]
        [NotNull()]
        public virtual IIS.Laba3.АктПогрРазгр АктПогрРазгр
        {
            get
            {
                // *** Start programmer edit section *** (ТЧАктПГ.АктПогрРазгр Get start)

                // *** End programmer edit section *** (ТЧАктПГ.АктПогрРазгр Get start)
                IIS.Laba3.АктПогрРазгр result = this.fАктПогрРазгр;
                // *** Start programmer edit section *** (ТЧАктПГ.АктПогрРазгр Get end)

                // *** End programmer edit section *** (ТЧАктПГ.АктПогрРазгр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧАктПГ.АктПогрРазгр Set start)

                // *** End programmer edit section *** (ТЧАктПГ.АктПогрРазгр Set start)
                this.fАктПогрРазгр = value;
                // *** Start programmer edit section *** (ТЧАктПГ.АктПогрРазгр Set end)

                // *** End programmer edit section *** (ТЧАктПГ.АктПогрРазгр Set end)
            }
        }
        
        /// <summary>
        /// ТЧАктПГ.
        /// </summary>
        // *** Start programmer edit section *** (ТЧАктПГ.Товар CustomAttributes)

        // *** End programmer edit section *** (ТЧАктПГ.Товар CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        [NotNull()]
        public virtual IIS.Laba3.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (ТЧАктПГ.Товар Get start)

                // *** End programmer edit section *** (ТЧАктПГ.Товар Get start)
                IIS.Laba3.Товар result = this.fТовар;
                // *** Start programmer edit section *** (ТЧАктПГ.Товар Get end)

                // *** End programmer edit section *** (ТЧАктПГ.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧАктПГ.Товар Set start)

                // *** End programmer edit section *** (ТЧАктПГ.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (ТЧАктПГ.Товар Set end)

                // *** End programmer edit section *** (ТЧАктПГ.Товар Set end)
            }
        }
    }
}
