//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Laba3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТЧПутевойЛ.
    /// </summary>
    // *** Start programmer edit section *** (ТЧПутевойЛ CustomAttributes)

    // *** End programmer edit section *** (ТЧПутевойЛ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ТЧПутевойЛ : ICSSoft.STORMNET.DataObject
    {
        
        private string fМестоНазнач;
        
        private int fПРойденоКМ;
        
        private string fМестоОтпр;
        
        private IIS.Laba3.ПутевойЛист fПутевойЛист;
        
        // *** Start programmer edit section *** (ТЧПутевойЛ CustomMembers)

        // *** End programmer edit section *** (ТЧПутевойЛ CustomMembers)

        
        /// <summary>
        /// МестоНазнач.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПутевойЛ.МестоНазнач CustomAttributes)

        // *** End programmer edit section *** (ТЧПутевойЛ.МестоНазнач CustomAttributes)
        [StrLen(255)]
        public virtual string МестоНазнач
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПутевойЛ.МестоНазнач Get start)

                // *** End programmer edit section *** (ТЧПутевойЛ.МестоНазнач Get start)
                string result = this.fМестоНазнач;
                // *** Start programmer edit section *** (ТЧПутевойЛ.МестоНазнач Get end)

                // *** End programmer edit section *** (ТЧПутевойЛ.МестоНазнач Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПутевойЛ.МестоНазнач Set start)

                // *** End programmer edit section *** (ТЧПутевойЛ.МестоНазнач Set start)
                this.fМестоНазнач = value;
                // *** Start programmer edit section *** (ТЧПутевойЛ.МестоНазнач Set end)

                // *** End programmer edit section *** (ТЧПутевойЛ.МестоНазнач Set end)
            }
        }
        
        /// <summary>
        /// МестоОтпр.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПутевойЛ.МестоОтпр CustomAttributes)

        // *** End programmer edit section *** (ТЧПутевойЛ.МестоОтпр CustomAttributes)
        [StrLen(255)]
        public virtual string МестоОтпр
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПутевойЛ.МестоОтпр Get start)

                // *** End programmer edit section *** (ТЧПутевойЛ.МестоОтпр Get start)
                string result = this.fМестоОтпр;
                // *** Start programmer edit section *** (ТЧПутевойЛ.МестоОтпр Get end)

                // *** End programmer edit section *** (ТЧПутевойЛ.МестоОтпр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПутевойЛ.МестоОтпр Set start)

                // *** End programmer edit section *** (ТЧПутевойЛ.МестоОтпр Set start)
                this.fМестоОтпр = value;
                // *** Start programmer edit section *** (ТЧПутевойЛ.МестоОтпр Set end)

                // *** End programmer edit section *** (ТЧПутевойЛ.МестоОтпр Set end)
            }
        }
        
        /// <summary>
        /// ПРойденоКМ.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПутевойЛ.ПРойденоКМ CustomAttributes)

        // *** End programmer edit section *** (ТЧПутевойЛ.ПРойденоКМ CustomAttributes)
        public virtual int ПРойденоКМ
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПутевойЛ.ПРойденоКМ Get start)

                // *** End programmer edit section *** (ТЧПутевойЛ.ПРойденоКМ Get start)
                int result = this.fПРойденоКМ;
                // *** Start programmer edit section *** (ТЧПутевойЛ.ПРойденоКМ Get end)

                // *** End programmer edit section *** (ТЧПутевойЛ.ПРойденоКМ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПутевойЛ.ПРойденоКМ Set start)

                // *** End programmer edit section *** (ТЧПутевойЛ.ПРойденоКМ Set start)
                this.fПРойденоКМ = value;
                // *** Start programmer edit section *** (ТЧПутевойЛ.ПРойденоКМ Set end)

                // *** End programmer edit section *** (ТЧПутевойЛ.ПРойденоКМ Set end)
            }
        }
        
        /// <summary>
        /// ТЧПутевойЛ.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПутевойЛ.ПутевойЛист CustomAttributes)

        // *** End programmer edit section *** (ТЧПутевойЛ.ПутевойЛист CustomAttributes)
        [PropertyStorage(new string[] {
                "ПутевойЛист"})]
        [NotNull()]
        public virtual IIS.Laba3.ПутевойЛист ПутевойЛист
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПутевойЛ.ПутевойЛист Get start)

                // *** End programmer edit section *** (ТЧПутевойЛ.ПутевойЛист Get start)
                IIS.Laba3.ПутевойЛист result = this.fПутевойЛист;
                // *** Start programmer edit section *** (ТЧПутевойЛ.ПутевойЛист Get end)

                // *** End programmer edit section *** (ТЧПутевойЛ.ПутевойЛист Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПутевойЛ.ПутевойЛист Set start)

                // *** End programmer edit section *** (ТЧПутевойЛ.ПутевойЛист Set start)
                this.fПутевойЛист = value;
                // *** Start programmer edit section *** (ТЧПутевойЛ.ПутевойЛист Set end)

                // *** End programmer edit section *** (ТЧПутевойЛ.ПутевойЛист Set end)
            }
        }
    }
}
